<a href="https://colab.research.google.com/github/HuyIt1412/DataAnalystDeepLearning/blob/master/labs/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Câu 1 Xác định và phân loại dữ liệu định tính và định lượng
 & 
 Câu 2* Định nghĩa các thang đo phù hợp cho từng biến số

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dataframe = pd.read_csv("https://raw.githubusercontent.com/huynhhoc/DataAnalystDeepLearning/main/Data/dulieuxettuyendaihoc.csv", index_col="STT");
print(dataframe)
print(dataframe.dtypes)

      T1   L1   H1   S1   V1   X1   D1  ...  GT  DT   KV   DH1   DH2   DH3  KT
STT                                     ...
1    7.2  7.3  6.3  7.3  7.0  7.9  7.3  ...   F NaN  2NT  3.25  3.25  4.50  A1
2    5.4  3.9  3.9  4.0  5.4  5.4  5.3  ...   M NaN    1  6.00  4.00  3.50   C
3    5.6  6.8  7.2  7.5  4.3  7.4  5.8  ...   M NaN    1  5.00  6.75  4.00   C
4    6.6  6.4  5.3  6.9  5.4  7.3  6.4  ...   M NaN    1  4.25  4.25  5.25  D1
5    6.0  5.0  6.0  7.3  6.5  7.7  7.9  ...   M NaN  2NT  4.25  4.50  5.00   A
..   ...  ...  ...  ...  ...  ...  ...  ...  ..  ..  ...   ...   ...   ...  ..
96   8.6  6.9  7.4  8.8  7.6  5.8  7.3  ...   F NaN    1  5.25  1.50  6.25   C
97   3.7  5.4  6.0  5.1  5.5  3.9  6.1  ...   F NaN    1  5.25  3.75  4.75   C
98   8.8  5.5  7.4  7.7  6.2  7.3  8.1  ...   M NaN  2NT  7.00  8.00  4.00   C
99   2.7  1.8  3.4  5.3  4.5  7.9  4.9  ...   M NaN    1  5.00  3.50  5.50   C
100  4.1  5.2  4.9  5.3  5.5  5.4  7.2  ...   M NaN  2NT  5.25  2.50  4.25   C

[100 rows x 55 columns]
T1     float64
L1     float64
H1     float64
S1     float64
V1     float64
X1     float64
D1     float64
N1     float64
T2     float64
L2     float64
H2     float64
S2     float64
V2     float64
X2     float64
D2     float64
N2     float64
T3     float64
L3     float64
H3     float64
S3     float64
V3     float64
X3     float64
D3     float64
N3     float64
T4     float64
L4     float64
H4     float64
S4     float64
V4     float64
X4     float64
D4     float64
N4     float64
T5     float64
L5     float64
H5     float64
S5     float64
V5     float64
X5     float64
D5     float64
N5     float64
T6     float64
L6     float64
H6     float64
S6     float64
V6     float64
X6     float64
D6     float64
N6     float64
GT      object
DT     float64
KV      object
DH1    float64
DH2    float64
DH3    float64
KT      object
dtype: object


**3.Sử dụng Python để tải dữ liệu lên chương trình và in ra màn hình 10 dòng đầu tiên và 10 dòng cuối cùng**

In [ ]:
dataframe.head(10)

      T1   L1   H1   S1   V1   X1   D1  ...  GT  DT   KV   DH1   DH2   DH3  KT
STT                                     ...
1    7.2  7.3  6.3  7.3  7.0  7.9  7.3  ...   F NaN  2NT  3.25  3.25  4.50  A1
2    5.4  3.9  3.9  4.0  5.4  5.4  5.3  ...   M NaN    1  6.00  4.00  3.50   C
3    5.6  6.8  7.2  7.5  4.3  7.4  5.8  ...   M NaN    1  5.00  6.75  4.00   C
4    6.6  6.4  5.3  6.9  5.4  7.3  6.4  ...   M NaN    1  4.25  4.25  5.25  D1
5    6.0  5.0  6.0  7.3  6.5  7.7  7.9  ...   M NaN  2NT  4.25  4.50  5.00   A
6    9.3  7.6  7.9  8.6  7.0  7.3  7.7  ...   M NaN    1  1.50  4.00  6.00  D1
7    2.8  3.9  5.5  6.9  5.0  7.3  4.6  ...   F NaN    2  6.50  6.75  5.25   C
8    8.3  6.0  7.6  5.1  7.5  4.7  5.8  ...   F NaN    2  3.75  4.50  4.25  D1
9    6.5  6.3  7.6  6.0  5.5  7.1  6.3  ...   F NaN    1  3.50  3.50  6.75  D1
10   7.3  5.9  4.7  7.1  6.7  7.9  6.7  ...   F NaN    1  4.00  4.75  5.50  D1

[10 rows x 55 columns]

In [ ]:
dataframe.tail(10)

      T1   L1   H1   S1   V1   X1   D1  ...  GT  DT   KV   DH1   DH2   DH3  KT
STT                                     ...
91   8.1  7.7  9.1  8.5  6.1  8.6  8.8  ...   M NaN    2  6.25  4.00  6.50   A
92   7.8  6.5  6.7  5.4  6.2  4.8  5.9  ...   M NaN  2NT  4.75  4.75  4.50   A
93   5.0  6.6  6.5  7.2  5.8  6.7  6.4  ...   M NaN    1  3.25  5.25  4.25   A
94   5.2  5.2  6.8  7.9  6.6  8.9  7.6  ...   M NaN    1  3.50  4.25  5.00   A
95   5.8  5.9  7.6  6.1  5.3  8.1  6.1  ...   M NaN    1  4.25  2.50  4.75   A
96   8.6  6.9  7.4  8.8  7.6  5.8  7.3  ...   F NaN    1  5.25  1.50  6.25   C
97   3.7  5.4  6.0  5.1  5.5  3.9  6.1  ...   F NaN    1  5.25  3.75  4.75   C
98   8.8  5.5  7.4  7.7  6.2  7.3  8.1  ...   M NaN  2NT  7.00  8.00  4.00   C
99   2.7  1.8  3.4  5.3  4.5  7.9  4.9  ...   M NaN    1  5.00  3.50  5.50   C
100  4.1  5.2  4.9  5.3  5.5  5.4  7.2  ...   M NaN  2NT  5.25  2.50  4.25   C

[10 rows x 55 columns]

**4.Thống kê dữ liệu thiếu cho cột dân tộc và hiệu chỉnh dữ liệu thiếu như sau: Mặc định thiếu thì điền giá trị 0.**

In [ ]:
dataframe["DT"].fillna(0,inplace = True)

In [ ]:
print(dataframe)

      T1   L1   H1   S1   V1   X1   D1  ...  GT   DT   KV   DH1   DH2   DH3  KT
STT                                     ...
1    7.2  7.3  6.3  7.3  7.0  7.9  7.3  ...   F  0.0  2NT  3.25  3.25  4.50  A1
2    5.4  3.9  3.9  4.0  5.4  5.4  5.3  ...   M  0.0    1  6.00  4.00  3.50   C
3    5.6  6.8  7.2  7.5  4.3  7.4  5.8  ...   M  0.0    1  5.00  6.75  4.00   C
4    6.6  6.4  5.3  6.9  5.4  7.3  6.4  ...   M  0.0    1  4.25  4.25  5.25  D1
5    6.0  5.0  6.0  7.3  6.5  7.7  7.9  ...   M  0.0  2NT  4.25  4.50  5.00   A
..   ...  ...  ...  ...  ...  ...  ...  ...  ..  ...  ...   ...   ...   ...  ..
96   8.6  6.9  7.4  8.8  7.6  5.8  7.3  ...   F  0.0    1  5.25  1.50  6.25   C
97   3.7  5.4  6.0  5.1  5.5  3.9  6.1  ...   F  0.0    1  5.25  3.75  4.75   C
98   8.8  5.5  7.4  7.7  6.2  7.3  8.1  ...   M  0.0  2NT  7.00  8.00  4.00   C
99   2.7  1.8  3.4  5.3  4.5  7.9  4.9  ...   M  0.0    1  5.00  3.50  5.50   C
100  4.1  5.2  4.9  5.3  5.5  5.4  7.2  ...   M  0.0  2NT  5.25  2.50  4.25   C

[100 rows x 55 columns]

**5.Thống kê dữ liệu thiếu cho biến T1 và hiệu chỉnh dữ liệu, lưu ý việc thay thế dữ liệu thiếu sử dụng phương pháp Mean**

In [ ]:
dataframe["T1"].fillna(df["T1"].mean(), inplace =True)

NameError: ignored

In [ ]:
print(dataframe)

      T1   L1   H1   S1   V1   X1   D1  ...  GT   DT   KV   DH1   DH2   DH3  KT
STT                                     ...
1    7.2  7.3  6.3  7.3  7.0  7.9  7.3  ...   F  0.0  2NT  3.25  3.25  4.50  A1
2    5.4  3.9  3.9  4.0  5.4  5.4  5.3  ...   M  0.0    1  6.00  4.00  3.50   C
3    5.6  6.8  7.2  7.5  4.3  7.4  5.8  ...   M  0.0    1  5.00  6.75  4.00   C
4    6.6  6.4  5.3  6.9  5.4  7.3  6.4  ...   M  0.0    1  4.25  4.25  5.25  D1
5    6.0  5.0  6.0  7.3  6.5  7.7  7.9  ...   M  0.0  2NT  4.25  4.50  5.00   A
..   ...  ...  ...  ...  ...  ...  ...  ...  ..  ...  ...   ...   ...   ...  ..
96   8.6  6.9  7.4  8.8  7.6  5.8  7.3  ...   F  0.0    1  5.25  1.50  6.25   C
97   3.7  5.4  6.0  5.1  5.5  3.9  6.1  ...   F  0.0    1  5.25  3.75  4.75   C
98   8.8  5.5  7.4  7.7  6.2  7.3  8.1  ...   M  0.0  2NT  7.00  8.00  4.00   C
99   2.7  1.8  3.4  5.3  4.5  7.9  4.9  ...   M  0.0    1  5.00  3.50  5.50   C
100  4.1  5.2  4.9  5.3  5.5  5.4  7.2  ...   M  0.0  2NT  5.25  2.50  4.25   C

[100 rows x 55 columns]


**6.Tạo các biến TBM1, TBM2, TBM3 tương ứng với trung bình môn của các năm lớp 10, 11 và 12. • Công thức tính: TBM = (T2 + L + H + S + V2 + X + D + N) / 10**

In [ ]:
for i in ['1','2','6']:
  dataframe['TBM'+i] = ( dataframe['T'+i]*2 + dataframe['L'+i] + dataframe['H'+i] + dataframe['S'+i] + dataframe['V'+i]*2 + dataframe['X'+i] + dataframe['D'+i] + dataframe['N'+i]) / 10
print(dataframe)

      T1   L1   H1   S1   V1   X1   D1  ...   DH1   DH2   DH3  KT  TBM1  TBM2  TBM6
STT                                     ...
1    7.2  7.3  6.3  7.3  7.0  7.9  7.3  ...  3.25  3.25  4.50  A1  7.00  7.54  7.01
2    5.4  3.9  3.9  4.0  5.4  5.4  5.3  ...  6.00  4.00  3.50   C  4.69  5.47  5.07
3    5.6  6.8  7.2  7.5  4.3  7.4  5.8  ...  5.00  6.75  4.00   C  5.77  5.38  6.04
4    6.6  6.4  5.3  6.9  5.4  7.3  6.4  ...  4.25  4.25  5.25  D1  6.21  5.20  6.88
5    6.0  5.0  6.0  7.3  6.5  7.7  7.9  ...  4.25  4.50  5.00   A  6.50  6.36  6.99
..   ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...  ..   ...   ...   ...
96   8.6  6.9  7.4  8.8  7.6  5.8  7.3  ...  5.25  1.50  6.25   C  7.43  7.42  6.83
97   3.7  5.4  6.0  5.1  5.5  3.9  6.1  ...  5.25  3.75  4.75   C  4.93  5.15  6.39
98   8.8  5.5  7.4  7.7  6.2  7.3  8.1  ...  7.00  8.00  4.00   C  7.05  7.84  7.67
99   2.7  1.8  3.4  5.3  4.5  7.9  4.9  ...  5.00  3.50  5.50   C  4.15  4.72  5.29
100  4.1  5.2  4.9  5.3  5.5  5.4  7.2  ...  5.25  2.50  4.25   C  5.26  5.72  5.85

[100 rows x 58 columns]

In [ ]:
dataframe.rename(columns={'TBM6':'TBM3'} , inplace=True)
print(dataframe)

      T1   L1   H1   S1   V1   X1   D1  ...   DH1   DH2   DH3  KT  TBM1  TBM2  TBM3
STT                                     ...
1    7.2  7.3  6.3  7.3  7.0  7.9  7.3  ...  3.25  3.25  4.50  A1  7.00  7.54  7.01
2    5.4  3.9  3.9  4.0  5.4  5.4  5.3  ...  6.00  4.00  3.50   C  4.69  5.47  5.07
3    5.6  6.8  7.2  7.5  4.3  7.4  5.8  ...  5.00  6.75  4.00   C  5.77  5.38  6.04
4    6.6  6.4  5.3  6.9  5.4  7.3  6.4  ...  4.25  4.25  5.25  D1  6.21  5.20  6.88
5    6.0  5.0  6.0  7.3  6.5  7.7  7.9  ...  4.25  4.50  5.00   A  6.50  6.36  6.99
..   ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...  ..   ...   ...   ...
96   8.6  6.9  7.4  8.8  7.6  5.8  7.3  ...  5.25  1.50  6.25   C  7.43  7.42  6.83
97   3.7  5.4  6.0  5.1  5.5  3.9  6.1  ...  5.25  3.75  4.75   C  4.93  5.15  6.39
98   8.8  5.5  7.4  7.7  6.2  7.3  8.1  ...  7.00  8.00  4.00   C  7.05  7.84  7.67
99   2.7  1.8  3.4  5.3  4.5  7.9  4.9  ...  5.00  3.50  5.50   C  4.15  4.72  5.29
100  4.1  5.2  4.9  5.3  5.5  5.4  7.2  ...  5.25  2.50  4.25   C  5.26  5.72  5.85

[100 rows x 58 columns]

**7. Tạo các biến xếp loại XL1, XL2 và XL3 dựa trên TBM1, TBM2 và TBM3 cho từng năm lớp 10, 11, 12 như sau: • Nhỏ hơn 5.0 xếp loại: yếu (kí hiệu là Y) • Từ 5.0 đến dưới 6.5: trung bình (kí hiệu là TB) • Từ 6.5 đến dưới 8.0: khá (kí hiệu là K) • Từ 8.0 đến dưới 9.0: giỏi (kí hiệu là G) • Từ 9.0 trở lên: xuất sắc (kí hiệu là XS)**

In [ ]:
for i in ['1','2','3']:
  dataframe.loc[dataframe['TBM'+i] < 5, 'XL'+i] = 'Y'
  dataframe.loc[(dataframe['TBM'+i] >= 5) & (dataframe['TBM'+i] < 6.5) , 'XL'+i] = 'TB' 
  dataframe.loc[(dataframe['TBM'+i] >= 6.5) & (dataframe['TBM'+i] < 8) , 'XL'+i] = 'K'
  dataframe.loc[(dataframe['TBM'+i] >= 8) & (dataframe['TBM'+i] < 9) , 'XL'+i] = 'G'
  dataframe.loc[(dataframe['TBM'+i] >= 9), 'XL'+i] = 'XS'  
print(dataframe)

      T1   L1   H1   S1   V1   X1   D1  ...  KT  TBM1  TBM2  TBM3  XL1  XL2  XL3
STT                                     ...
1    7.2  7.3  6.3  7.3  7.0  7.9  7.3  ...  A1  7.00  7.54  7.01    K    K    K
2    5.4  3.9  3.9  4.0  5.4  5.4  5.3  ...   C  4.69  5.47  5.07    Y   TB   TB
3    5.6  6.8  7.2  7.5  4.3  7.4  5.8  ...   C  5.77  5.38  6.04   TB   TB   TB
4    6.6  6.4  5.3  6.9  5.4  7.3  6.4  ...  D1  6.21  5.20  6.88   TB   TB    K
5    6.0  5.0  6.0  7.3  6.5  7.7  7.9  ...   A  6.50  6.36  6.99    K   TB    K
..   ...  ...  ...  ...  ...  ...  ...  ...  ..   ...   ...   ...  ...  ...  ...
96   8.6  6.9  7.4  8.8  7.6  5.8  7.3  ...   C  7.43  7.42  6.83    K    K    K
97   3.7  5.4  6.0  5.1  5.5  3.9  6.1  ...   C  4.93  5.15  6.39    Y   TB   TB
98   8.8  5.5  7.4  7.7  6.2  7.3  8.1  ...   C  7.05  7.84  7.67    K    K    K
99   2.7  1.8  3.4  5.3  4.5  7.9  4.9  ...   C  4.15  4.72  5.29    Y    Y   TB
100  4.1  5.2  4.9  5.3  5.5  5.4  7.2  ...   C  5.26  5.72  5.85   TB   TB   TB

[100 rows x 61 columns]

**8.Tạo các biến US_TBM1, US_TBM2 và US_TBM3 để chuyển điểm trung bình các năm lớp 10, 11 và 12 từ thang điểm 10 của Việt Nam sang thang điểm 4 của Mỹ. Sử dụng phương pháp Min-Max Normalization**

In [ ]:
for i in ['1','2','3']:
  dataframe['US_TBM'+i] = dataframe['TBM'+i]/10 * 4
print(dataframe.head())

      T1   L1   H1   S1   V1   X1  ...  XL1  XL2  XL3  US_TBM1  US_TBM2  US_TBM3
STT                                ...
1    7.2  7.3  6.3  7.3  7.0  7.9  ...    K    K    K    2.800    3.016    2.804
2    5.4  3.9  3.9  4.0  5.4  5.4  ...    Y   TB   TB    1.876    2.188    2.028
3    5.6  6.8  7.2  7.5  4.3  7.4  ...   TB   TB   TB    2.308    2.152    2.416
4    6.6  6.4  5.3  6.9  5.4  7.3  ...   TB   TB    K    2.484    2.080    2.752
5    6.0  5.0  6.0  7.3  6.5  7.7  ...    K   TB    K    2.600    2.544    2.796

[5 rows x 64 columns]


**9.Tạo biến kết quả xét tuyển (kí hiệu là KQXT) nhằm xác định sinh viên đậu (giá trị “1”) và rớt (giá trị “0”) vào các khối dựa trên điểm DH1, DH2 và DH3 như sau • Với khối A, A1 nếu [((DH1)x2 + DH2 + DH3)/4] lớn hơn hoặc bằng 5.0 thì đậu, ngược lại là rớt • Với khối B nếu [(DH1 + (DH2)x*2 + DH3)/4] lớn hơn hoặc bằng 5.0 thì đậu, ngược lại là rớt • Với khối khác nếu [(DH1+ DH2 + DH3)/3] lớn hơn hoặc bằng 5.0 thì đậu, ngược lại là rớt**

In [18]:
for i in dataframe['KT'].unique():
    str(i)
    dataframe.loc[(i == 'A1' or i == 'A') & (((dataframe['DH1']*2 + dataframe['DH2'] + dataframe['DH3'])/4) >= 5), 'KQXT'] = '1'
    dataframe.loc[(i == 'A1' or i == 'A') & (((dataframe['DH1']*2 + dataframe['DH2'] + dataframe['DH3'])/4) < 5), 'KQXT'] = '0'
    
    dataframe.loc[(i == 'B') & (((dataframe['DH1'] + dataframe['DH2']*2 + dataframe['DH3'])/4) >= 5), 'KQXT'] = '1'
    dataframe.loc[(i == 'B') & (((dataframe['DH1'] + dataframe['DH2']*2 + dataframe['DH3'])/4) < 5), 'KQXT'] = '0'
    
    dataframe.loc[(i != 'A1' and i != 'A' and i != 'B') & (((dataframe['DH1'] + dataframe['DH2'] + dataframe['DH3'])/3) >= 5), 'KQXT'] = '1'
    dataframe.loc[(i != 'A1' and i != 'A' and i != 'B') & (((dataframe['DH1'] + dataframe['DH2'] + dataframe['DH3'])/3) < 5), 'KQXT'] = '0'

print(dataframe)

      T1   L1   H1   S1   V1   X1  ...  XL2  XL3  US_TBM1  US_TBM2  US_TBM3  KQXT
STT                                ...
1    7.2  7.3  6.3  7.3  7.0  7.9  ...    K    K    2.800    3.016    2.804     0
2    5.4  3.9  3.9  4.0  5.4  5.4  ...   TB   TB    1.876    2.188    2.028     0
3    5.6  6.8  7.2  7.5  4.3  7.4  ...   TB   TB    2.308    2.152    2.416     1
4    6.6  6.4  5.3  6.9  5.4  7.3  ...   TB    K    2.484    2.080    2.752     0
5    6.0  5.0  6.0  7.3  6.5  7.7  ...   TB    K    2.600    2.544    2.796     0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...      ...      ...      ...   ...
96   8.6  6.9  7.4  8.8  7.6  5.8  ...    K    K    2.972    2.968    2.732     0
97   3.7  5.4  6.0  5.1  5.5  3.9  ...   TB   TB    1.972    2.060    2.556     0
98   8.8  5.5  7.4  7.7  6.2  7.3  ...    K    K    2.820    3.136    3.068     1
99   2.7  1.8  3.4  5.3  4.5  7.9  ...    Y   TB    1.660    1.888    2.116     0
100  4.1  5.2  4.9  5.3  5.5  5.4  ...   TB   TB    2.104    2.288    2.340     0

[100 rows x 65 columns]

**10.Lưu trữ dữ liệu xuống ổ đĩa thành file processed_dulieuxettuyendaihoc.csv**

In [ ]:
dataframe.to_csv('processed_dulieuxettuyendaihoc.csv')